###

# curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://localhost:8083/connectors/ -d '{
#    "name": "mysql-connector",
#    "config": {
#        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
#        "database.hostname": "mysql",
#        "database.port": "3306",
#        "database.user": "user",
#        "database.password": "password",
#        "database.server.id": "1",
#        "database.server.name": "mysql-server",
#        "database.whitelist": "testdb",
#        "database.history.kafka.bootstrap.servers": "kafka:9092",
#        "database.history.kafka.topic": "schema-changes.testdb",
#        "include.schema.changes": "true",
#        "topic.prefix": "mysql-"
#    }
#}'
POST http://localhost:8083/connectors/
Accept: application/json
Content-Type: application/json

{
  "name": "mysql-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "mysql",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "rootpassword",
    "database.server.id": "1",
    "database.server.name": "mysql-server",
    "database.whitelist": "testdb",
    "schema.history.internal.kafka.topic": "dbhistory.your-database-name",
    "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
    "include.schema.changes": "true",
    "topic.prefix": "mysql_"
  }
}

###

# curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://127.0.0.1:8083/connectors/ -d '{
#    "name": "mongodb-connector",
#    "config": {
#        "connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
#        "mongodb.hosts": "mongodb:27017",
#        "mongodb.user": "root",
#        "mongodb.password": "rootpassword",
#        "mongodb.name": "testdb",
#        "database.whitelist": "testdb",
#        "tasks.max": "1",
#        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
#        "value.converter": "org.apache.kafka.connect.json.JsonConverter"
#    }
#}'
POST http://127.0.0.1:8083/connectors/
Accept: application/json
Content-Type: application/json

{
  "name": "mongodb-connector",
  "config": {
    "connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
    "mongodb.hosts": "mongodb:27017",
    "mongodb.user": "root",
    "mongodb.password": "rootpassword",
    "mongodb.name": "testdb",
    "database.whitelist": "testdb",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "topic.prefix": "mongodb_"
  }
}

###

